dance_db_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),

    path('artist/<int:artist_id>/', views.view_artist, name="view_artist"),
    path('track/<int:track_id>/', views.view_track, name="view_track"),
    path('dance/<int:dance_id>/', views.view_dance, name="view_dance"),

    path('artist/add/', views.view_add_artist, name="view_add_artist"),
    path('track/add/', views.view_add_track, name="view_add_track"),
    path('dance/add/', views.view_add_dance, name="view_add_dance"),

    path('dance/<int:dance_id>/edit/', views.view_edit_dance, name="view_edit_dance"),

    path('artists/', views.view_artists, name="view_all_artists"),
    path('tracks/', views.view_tracks, name="view_all_tracks"),
    path('dances/', views.view_dances, name="view_all_dances"),
]

danceclub/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dance_db_app.urls')),
]

dance_db_app/models.py
from django.db import models

# Create your models here.
class Artist(models.Model):
    name = models.CharField(max_length=256)
    country = models.CharField(max_length=100)
    birthday = models.DateField()

    def get_tracks_count(self):
        return self.track_set.count()

    def __str__(self):
        return self.name

class Track(models.Model):
    title = models.CharField(max_length=256)
    duration = models.IntegerField()
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)

    def __str__(self):
        return self.artist.name + ' - ' + self.title

class Dance(models.Model):
    title = models.CharField(max_length=256)
    difficulty = models.IntegerField()
    track = models.ForeignKey(Track, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

dance_db_app/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.http import HttpResponse, Http404
from .models import Artist, Track, Dance

# Create your views here.
def index(request):
    latest_artists_list = Artist.objects.order_by('-id')[:3]
    latest_tracks_list = Track.objects.order_by('-id')[:3]
    latest_dances_list = Dance.objects.order_by('-id')[:3]

    template = loader.get_template('dance_db_app/index.html')
    context = {
        'artists': latest_artists_list,
        'tracks': latest_tracks_list,
        'dances': latest_dances_list,
    }
    return HttpResponse(template.render(context, request))

def view_artist(request, artist_id):
    artist = get_object_or_404(Artist, pk=artist_id)
    return render(request, 'dance_db_app/artist.html', {'artist': artist})

def view_track(request, track_id):
    track = get_object_or_404(Track, pk=track_id)
    return render(request, 'dance_db_app/track.html', {'track': track})

def view_dance(request, dance_id):
    dance = get_object_or_404(Dance, pk=dance_id)
    return render(request, 'dance_db_app/dance.html', {'dance': dance})

def view_artists(request):
    template = loader.get_template('dance_db_app/artists.html')
    context = {
        'artists': Artist.objects.all()
    }
    return HttpResponse(template.render(context, request))

def view_tracks(request):
    template = loader.get_template('dance_db_app/tracks.html')
    context = {
        'tracks': Track.objects.all()
    }
    return HttpResponse(template.render(context, request))

def view_dances(request):
    template = loader.get_template('dance_db_app/dances.html')
    context = {
        'dances': Dance.objects.all()
    }
    return HttpResponse(template.render(context, request))

def view_add_artist(request):
    template = loader.get_template('dance_db_app/add_artist.html')
    context = {

    }
    if all(['artist_name' in request.POST, 'artist_birthday' in request.POST, 'artist_country' in request.POST]):
        artist = Artist(name=request.POST['artist_name'], birthday=request.POST['artist_birthday'], country=request.POST['artist_country'])
        artist.save()
        context['msg'] = f'Артист {request.POST["artist_name"]} успешно добавлен!'
    return HttpResponse(template.render(context, request))

def view_add_track(request):
    template = loader.get_template('dance_db_app/add_track.html')
    context = {
        'artists': Artist.objects.all()
    }
    if all(['artist_id' in request.POST, 'track_title' in request.POST, 'track_duration' in request.POST]):
        track_artist = get_object_or_404(Artist, pk=request.POST['artist_id'])
        track = Track(title=request.POST['track_title'], duration=request.POST['track_duration'], artist=track_artist)
        track.save()
        context['msg'] = f'Трек {request.POST["track_title"]} успешно добавлен!'
    return HttpResponse(template.render(context, request))

def view_add_dance(request):
    template = loader.get_template('dance_db_app/add_dance.html')
    context = {
        'tracks': Track.objects.all()
    }
    if all(['track_id' in request.POST, 'dance_title' in request.POST, 'dance_difficulty' in request.POST]):
        dance_track = get_object_or_404(Track, pk=request.POST['track_id'])
        dance = Dance(title=request.POST['dance_title'], difficulty=request.POST['dance_difficulty'], track=dance_track)
        dance.save()
        context['msg'] = f'Танец {request.POST["dance_title"]} успешно добавлен!'
    return HttpResponse(template.render(context, request))

def view_edit_dance(request, dance_id):
    template = loader.get_template('dance_db_app/edit_dance.html')
    dance = get_object_or_404(Dance, pk=dance_id)
    context = {
        'dance': dance,
        'tracks': Track.objects.all()
    }
    if all(['track_id' in request.POST, 'dance_title' in request.POST, 'dance_difficulty' in request.POST]):
        dance.track = get_object_or_404(Track, pk=request.POST['track_id'])
        dance.title = request.POST['dance_title']
        dance.difficulty = request.POST['dance_difficulty']
        dance.save()
        context['msg'] = f'Танец изменен!'
    return HttpResponse(template.render(context, request))

dance_db_app/templates/dance_db_app/add_artist.html
{% extends 'dance_db_app/blocks/page_base.html' %}

{% block page_title %}Добавление артиста{% endblock page_title %}

{% block page_content %}

<div class="container-fluid">
    <form action="{% url 'view_add_artist' %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <label class="form-label" for="artist_name">Имя артиста</label>
            <input class="form-control" type="text" name="artist_name" required>
            <br>
            <label class="form-label" for="artist_birthday">ДР артиста (yyyy-mm-dd)</label>
            <input class="form-control" type="text" name="artist_birthday" required>
            <br>
            <label class="form-label" for="artist_country">Страна артиста</label>
            <input class="form-control" type="text" name="artist_country" required>
            <br>
            <input type="submit" class="btn btn-primary">
        </fieldset>
    </form>

    {% if msg %}<h4 class="mt-4">{{ msg }}</h4>{% endif %}
</div>
    

{% endblock page_content %}

dance_db_app/templates/dance_db_app/add_dance.html
{% extends 'dance_db_app/blocks/page_base.html' %}

{% block page_title %}Добавление танца{% endblock page_title %}

{% block page_content %}

<div class="container-fluid">
    <form action="{% url 'view_add_dance' %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <label class="form-label" for="track_id">Трек</label>
            <select class="form-select" aria-label="Default select example" name="track_id" required>
                {% for track in tracks %}
                <option value="{{track.pk}}">{{track.artist.name}} - {{track.title}}</option>
                {% endfor %}
            </select>
            <br>
            <label class="form-label" for="dance_title">Название танца</label>
            <input class="form-control" type="text" name="dance_title" required>
            <br>
            <label class="form-label" for="dance_difficulty">Сложность танца</label>
            <input class="form-control" type="number" name="dance_difficulty" required>
            <br>
            <input type="submit" class="btn btn-primary">

        </fieldset>
    </form>

    {% if msg %}<h4 class="mt-4">{{ msg }}</h4>{% endif %}
</div>
    

{% endblock page_content %}

dance_db_app/templates/dance_db_app/add_track.html
{% extends 'dance_db_app/blocks/page_base.html' %}

{% block page_title %}Добавление трека{% endblock page_title %}

{% block page_content %}

<div class="container-fluid">
    <form action="{% url 'view_add_track' %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <label class="form-label" for="artist_id">Артиста</label>
            <select class="form-select" aria-label="Default select example" name="artist_id" required>
                {% for artist in artists %}
                <option value="{{artist.pk}}">{{artist.name}}</option>
                {% endfor %}
            </select>
            <br>
            <label class="form-label" for="track_title">Название трека</label>
            <input class="form-control" type="text" name="track_title" required>
            <br>
            <label class="form-label" for="track_duration">Длительность трека (сек)</label>
            <input class="form-control" type="number" name="track_duration" required>
            <br>
            <input type="submit" class="btn btn-primary">
        </fieldset>
    </form>

    {% if msg %}<h4 class="mt-4">{{ msg }}</h4>{% endif %}
</div>
    

{% endblock page_content %}

dance_db_app/templates/dance_db_app/artist.html
{% extends 'dance_db_app/blocks/page_base.html' %}

{% block page_title %}Карточка артиста{% endblock page_title %}

{% block page_content %}

<div class="container-fluid">
    <div>
        <span class="h3 align-middle">{{artist.name}}</span>
        <img class="ms-2 float-top align-middle" src="https://flagsapi.com/{{artist.country}}/flat/32.png">
    </div>
    <p>День рождения: {{artist.birthday}}</p>
    <p>Треки:</p>
    <table class="table table-hover">
        <tr>
            <th>Название</th>
            <th>Длина</th>
        </tr>
        {% for track in artist.track_set.all %}
        <tr style="cursor: pointer" onclick="window.location='{% url 'view_track' track.pk %}'">
            <td>{{track.title}}</td>
            <td>{{track.duration}}</td>
        </tr>
        {% endfor %}
    </table>
        
</div>
    

{% endblock page_content %}

dance_db_app/templates/dance_db_app/artists.html
{% extends 'dance_db_app/blocks/page_base.html' %}

{% block page_title %}Список артистов{% endblock page_title %}

{% block page_content %}

<table class="table table-hover">
    <tr>
        <th>Имя</th>
        <th>День рождения</th>
        <th>Страна</th>
    </tr>
    {% for artist in artists %}
    <tr style="cursor: pointer" onclick="window.location='{% url 'view_artist' artist.pk %}'">
        <td>{{artist.name}}</td>
        <td>{{artist.birthday}}</td>
        <td>{{artist.country}}</td>
    </tr>
    {% endfor %}
</table>
    

{% endblock page_content %}

dance_db_app/templates/dance_db_app/blocks/page_base.html
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">

    <title>База танцующих данных</title>
</head>
<body>
    <div class="bg-body ps-4 py-2 shadow-sm">
        <a href="{% url 'index' %}" style="display: inline; font-size: 2rem" class="bi bi-house-fill link-dark"></a>
        <h2 style="display: inline" class="ms-2">{% block page_title %}Имя раздела{% endblock page_title %}</h2>
    </div>
    <div class="bg-body px-5 mt-4">
        {% block page_content %}Контент{% endblock page_content %}
    </div>
</body>
</html>

dance_db_app/templates/dance_db_app/blocks/snippet_artist.html
<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{artist.name}}</h5>
        <p class="card-text">Количество треков: {{artist.get_tracks_count}}</p>

        <a href="{% url 'view_artist' artist_id %}" class="btn btn-primary">Посмотреть</a>
    </div>
</div>

dance_db_app/templates/dance_db_app/blocks/snippet_dance.html
<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{dance.title}}</h5>
        <p class="card-text">Под трек: {{dance.track.artist.name}} - {{dance.track.title}}</p>

        <a href="{% url 'view_dance' dance_id %}" class="btn btn-primary">Посмотреть</a>
    </div>
</div>

dance_db_app/templates/dance_db_app/blocks/snippet_track.html
<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{track.title}}</h5>
        <p class="card-text">Артист: {{track.artist.name}}</p>

        <a href="{% url 'view_track' track_id %}" class="btn btn-primary">Посмотреть</a>
    </div>
</div>

dance_db_app/templates/dance_db_app/dance.html
{% extends 'dance_db_app/blocks/page_base.html' %}

{% block page_title %}Просмотр танца{% endblock page_title %}

{% block page_content %}

<div class="container-fluid">
    <div>
        <span class="h3 align-middle">{{dance.title}}</span>
    </div>
    <p>Сложность: <strong>{{dance.difficulty}} звезд</strong></p>
    <p>Трек: <a class="link-primary" href="{% url 'view_track' dance.track.pk %}">{{dance.track.artist.name}} - {{dance.track.title}}</a></strong></p>
    <a class="h4 link-primary" href="{% url 'view_edit_dance' dance.pk %}">Редактировать</a>
</div>
    

{% endblock page_content %}

dance_db_app/templates/dance_db_app/dances.html
{% extends 'dance_db_app/blocks/page_base.html' %}

{% block page_title %}Список танцев{% endblock page_title %}

{% block page_content %}

<table class="table table-hover">
    <tr>
        <th>Название</th>
        <th>Под трек</th>
    </tr>
    {% for dance in dances %}
    <tr style="cursor: pointer" onclick="window.location='{% url 'view_dance' dance.pk %}'">
        <td>{{dance.title}}</td>
        <td>{{dance.track.artist.name}} - {{dance.track.title}}</td>
    </tr>
    {% endfor %}
</table>
    

{% endblock page_content %}

dance_db_app/templates/dance_db_app/edit_dance.html
{% extends 'dance_db_app/blocks/page_base.html' %}

{% block page_title %}Редактирование танца{% endblock page_title %}

{% block page_content %}

<div class="container-fluid">
    <form action="{% url 'view_edit_dance' dance.pk %}" method="POST">
        {% csrf_token %}
        <fieldset>
            <label class="form-label" for="track_id">Трек</label>
            <select class="form-select" aria-label="Default select example" name="track_id" required>
                {% for track in tracks %}
                <option {% if track.pk == dance.track.pk %}selected="selected"{% endif %} value="{{track.pk}}">{{track.artist.name}} - {{track.title}}</option>
                {% endfor %}
            </select>
            <br>
            <label class="form-label" for="dance_title">Название танца</label>
            <input class="form-control" type="text" name="dance_title" value="{{dance.title}}" required>
            <br>
            <label class="form-label" for="dance_difficulty">Сложность танца</label>
            <input class="form-control" type="number" name="dance_difficulty" value="{{dance.difficulty}}" required>
            <br>
            <input type="submit" class="btn btn-primary">

        </fieldset>
    </form>

    {% if msg %}<h4 class="mt-4">{{ msg }}</h4>{% endif %}
</div>
    

{% endblock page_content %}

dance_db_app/templates/dance_db_app/index.html
{% extends 'dance_db_app/blocks/page_base.html' %}

{% block page_title %}Добро пожаловать!{% endblock page_title %}

{% block page_content %}

<div class="container-fluid text-center">
    <div class="row">
        <div class="col">
            <div class="mb-4">
            <h3 class="d-inline">Артисты</h3>
            <a href="{% url 'view_add_artist' %}" style="link-primary; font-size: 1.75rem" class="d-inline bi bi-plus-square ms-2"></a>
            </div>
            {% if artists %}
                {% for artist in artists %}
                    <div class="mb-4 mx-4">
                        {% include "dance_db_app/blocks/snippet_artist.html" with artist=artist artist_id=artist.pk%}
                    </div>
                {% endfor %}
            {% endif %}
            <a href="{% url 'view_all_artists' %}" class="link-primary h3">Показать все</a>
        </div>
        <div class="col">
            <div class="mb-4">
                <h3 class="d-inline">Треки</h3>
                <a href="{% url 'view_add_track' %}" style="link-primary; font-size: 1.75rem" class="d-inline bi bi-plus-square ms-2"></a>
                </div>
            {% if tracks %}
                {% for track in tracks %}
                    <div class="mb-4 mx-4">
                        {% include "dance_db_app/blocks/snippet_track.html" with track=track track_id=track.pk%}
                    </div>
                {% endfor %}
            {% endif %}
            <a href="{% url 'view_all_tracks' %}" class="link-primary h3">Показать все</a>
        </div>
        <div class="col">
            <div class="mb-4">
                <h3 class="d-inline">Танцы</h3>
                <a href="{% url 'view_add_dance' %}" style="link-primary; font-size: 1.75rem" class="d-inline bi bi-plus-square ms-2"></a>
                </div>
            {% if dances %}
                {% for dance in dances %}
                    <div class="mb-4 mx-4">
                        {% include "dance_db_app/blocks/snippet_dance.html" with dance=dance dance_id=dance.pk%}
                    </div>
                {% endfor %}
            {% endif %}
            <a href="{% url 'view_all_dances' %}" class="link-primary h3">Показать все</a>
        </div>
    </div>
</div>
    

{% endblock page_content %}

dance_db_app/templates/dance_db_app/track.html
{% extends 'dance_db_app/blocks/page_base.html' %}

{% block page_title %}Просмотр трека{% endblock page_title %}

{% block page_content %}

<div class="container-fluid">
    <div>
        <span class="h3 align-middle"><a class="link-dark" href="{% url 'view_artist' track.artist.pk %}">{{track.artist.name}}</a> - {{track.title}}</span>
    </div>
    <p>Длина трека: <strong>{{track.duration}} сек.</strong></p>
    <p>Танцы под этот трек:</p>
    <table class="table table-hover">
        <tr>
            <th>Название</th>
            <th>Сложность</th>
        </tr>
        {% for dance in track.dance_set.all %}
        <tr style="cursor: pointer" onclick="window.location='{% url 'view_dance' dance.pk %}'">
            <td>{{dance.title}}</td>
            <td>{{dance.difficulty}}</td>
        </tr>
        {% endfor %}
    </table>
        
</div>
    

{% endblock page_content %}

dance_db_app/templates/dance_db_app/tracks.html
{% extends 'dance_db_app/blocks/page_base.html' %}

{% block page_title %}Список треков{% endblock page_title %}

{% block page_content %}

<table class="table table-hover">
    <tr>
        <th>Артист</th>
        <th>Название</th>
    </tr>
    {% for track in tracks %}
    <tr style="cursor: pointer" onclick="window.location='{% url 'view_track' track.pk %}'">
        <td>{{track.artist.name}}</td>
        <td>{{track.title}}</td>
    </tr>
    {% endfor %}
</table>
    

{% endblock page_content %}